# -*- coding: utf-8 -*-
"""
과제 6/7 대시보드용 임베드 데이터 생성 스크립트.

data/housePricing_selected.csv 를 읽어서
 - 행 단위 최소 컬럼(필터/차트 재계산용)
 - 전역 요약 통계(KPI, 상관계수 등)
를 담은 JS 파일(data.js)을 생성한다.

fetch() 는 file:// 에서 CORS 로 막히므로, 결과를 `const DASH_DATA = {...}` 형태의
classic script 로 내보내서 <script src="data.js"> 로 로드한다(= 인라인 임베드와 동일 효과).

사용법:  python build_data.py
"""
import csv
import json
import math
import os

BASE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(BASE)
CSV_PATH = os.path.join(ROOT, "data", "housePricing_selected.csv")

# 대시보드에서 실제로 쓰는 컬럼만 임베드 (파일 크기 관리)
NUM_COLS = ["OverallQual", "GrLivArea", "GarageCars", "TotalBsmtSF",
            "FullBath", "YearBuilt", "Fireplaces", "SalePrice"]
CAT_COLS = ["Neighborhood"]


def pearson(xs, ys):
    n = len(xs)
    if n < 2:
        return 0.0
    mx = sum(xs) / n
    my = sum(ys) / n
    sxy = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    sxx = sum((x - mx) ** 2 for x in xs)
    syy = sum((y - my) ** 2 for y in ys)
    if sxx <= 0 or syy <= 0:
        return 0.0
    return sxy / math.sqrt(sxx * syy)


def main():
    rows = []
    with open(CSV_PATH, "r", encoding="utf-8-sig", newline="") as f:
        for r in csv.DictReader(f):
            rec = {}
            for c in NUM_COLS:
                rec[c] = int(float(r[c]))
            for c in CAT_COLS:
                rec[c] = r[c]
            rows.append(rec)

    prices = [r["SalePrice"] for r in rows]
    n = len(prices)
    mean = sum(prices) / n
    sd = math.sqrt(sum((p - mean) ** 2 for p in prices) / (n - 1))
    skew = (n / ((n - 1) * (n - 2))) * sum(((p - mean) / sd) ** 3 for p in prices)

    corr = {}
    for c in NUM_COLS:
        if c == "SalePrice":
            continue
        corr[c] = round(pearson([r[c] for r in rows], prices), 3)
    top_corr = sorted(corr.items(), key=lambda kv: -abs(kv[1]))

    meta = {
        "source": "data/housePricing_selected.csv (다중공선성 제거본)",
        "nRows": n,
        "meanPrice": round(mean, 2),
        "maxPrice": max(prices),
        "minPrice": min(prices),
        "sdPrice": round(sd, 2),
        "skewPrice": round(skew, 3),
        "corrWithSalePrice": corr,
        "topDrivers": [{"feature": k, "r": v} for k, v in top_corr[:4]],
        "droppedCollinear": [
            {"feature": "GarageArea", "reason": "GarageCars 와 r=0.88"},
            {"feature": "TotRmsAbvGrd", "reason": "GrLivArea 와 r=0.83"},
            {"feature": "1stFlrSF", "reason": "TotalBsmtSF 와 r=0.82"},
        ],
        "neighborhoods": sorted({r["Neighborhood"] for r in rows}),
        "qualities": sorted({r["OverallQual"] for r in rows}),
    }

    payload = {"meta": meta, "rows": rows}
    js = ("// AUTO-GENERATED by build_data.py -- 직접 수정하지 말 것\n"
          "const DASH_DATA = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n")

    for out_dir in (BASE, os.path.join(ROOT, "07_ollama")):
        os.makedirs(out_dir, exist_ok=True)
        out = os.path.join(out_dir, "data.js")
        with open(out, "w", encoding="utf-8") as f:
            f.write(js)
        print("wrote %s (%.1f KB)" % (out, os.path.getsize(out) / 1024))

    print(json.dumps(meta, ensure_ascii=False, indent=2)[:800])


if __name__ == "__main__":
    main()
